# build environment
FROM node:13.12.0-alpine as build
WORKDIR /usr/src
COPY ./ /usr/src
RUN yarn install
RUN yarn build

# production environment
FROM nginx:stable-alpine
COPY --from=build /usr/src/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]