version: '3.7'

services:
  app:
    container_name: app-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - EXTEND_ESLINT=false
      - PORT=3000
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 3000:3000
