version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
  cypress: cypress-io/cypress@1
jobs:
  run-test:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Run lint code
          command: |
            mkdir -p ~/reports
            yarn eslint . --format junit --output-file ~/reports/eslint.xml
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
      - run:
          name: Run intergration test with coverage
          command: yarn test:ci --coverage
      - codecov/upload:
          file: './coverage/clover.xml'
          token: $CODECOV_TOKEN
workflows:
  intergration_test:
    jobs:
      - run-test
  e2e_test:
    jobs:
      - cypress/run:
          yarn: true
          build: yarn build
          start: yarn serve
          wait-on: $CYPRESS_BASE_URL
          record: true
          executor: cypress/browsers-chrome69
          browser: chrome
          working_directory: e2e
