version: '3.2'

# run Cypress tests and exit with command
#   docker-compose up --exit-code-from cypress
services:
  # this is the web application we are going to test
  app:
    build:
      context: ../
      dockerfile: Dockerfile.prod
    ports:
      - '80'
  # Cypress container
  cypress:
    # the Docker image to use from https://github.com/cypress-io/cypress-docker-images
    image: 'cypress/included:4.0.2'
    links:
      - app:app
    depends_on:
      - app
    environment:
      # pass base url to test pointing at the web application
      - CYPRESS_baseUrl=http://app:80
      - CYPRESS_RECORD_KEY=323eab11-5923-4c1e-9933-d947acca862d
    # share the current folder as volume to avoid copying
    working_dir: /e2e
    volumes:
      - .:/e2e
    entrypoint: cypress run --record
